// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_WEB_KEY',
      defaultValue: 'KEY_NOT_FOUND',
    ),
    authDomain: "health-diary-a5487.firebaseapp.com",
    projectId: "health-diary-a5487",
    storageBucket: "health-diary-a5487.firebasestorage.app",
    messagingSenderId: "94811852495",
    appId: "1:94811852495:web:62e0d1910b0cb59fcff1ba",
    measurementId: "G-R6RN3MFRPW",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_ANDROID_KEY',
      defaultValue: 'KEY_NOT_FOUND',
    ),
    appId: '1:94811852495:android:09b8a589f76bb382cff1ba',
    messagingSenderId: '94811852495',
    projectId: 'health-diary-a5487',
    storageBucket: 'health-diary-a5487.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_IOS_KEY',
      defaultValue: 'KEY_NOT_FOUND',
    ),
    appId: '1:94811852495:ios:6fc3b044948387bacff1ba',
    messagingSenderId: '94811852495',
    projectId: 'health-diary-a5487',
    storageBucket: 'health-diary-a5487.firebasestorage.app',
    iosBundleId: 'com.example.healthDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_MACOS_KEY',
      defaultValue: 'KEY_NOT_FOUND',
    ),
    appId: '1:94811852495:ios:6fc3b044948387bacff1ba',
    messagingSenderId: '94811852495',
    projectId: 'health-diary-a5487',
    storageBucket: 'health-diary-a5487.firebasestorage.app',
    iosBundleId: 'com.example.healthDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_WINDOWS_KEY',
      defaultValue: 'KEY_NOT_FOUND',
    ),
    appId: '1:94811852495:web:33733b619f692218cff1ba',
    messagingSenderId: '94811852495',
    projectId: 'health-diary-a5487',
    authDomain: 'health-diary-a5487.firebaseapp.com',
    storageBucket: 'health-diary-a5487.firebasestorage.app',
    measurementId: 'G-H0P7ED99YX',
  );
}
